name: RoonController
options:
  bundleIdPrefix: com.bertrand
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

targets:
  RoonController:
    type: application
    platform: macOS
    sources:
      - path: .
        excludes:
          - project.yml
          - "*.xcodeproj"
          - "*.xcworkspace"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bertrand.RoonController
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_GENERATION_LIBRARY: YES
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "6.0"
        CODE_SIGN_ENTITLEMENTS: RoonController.entitlements
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: "Roon Controller"
