name: RoonController
options:
  bundleIdPrefix: com.bertrand
  deploymentTarget:
    macOS: "12.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

targets:
  RoonController:
    type: application
    platform: macOS
    sources:
      - path: .
        excludes:
          - project.yml
          - "*.xcodeproj"
          - "*.xcworkspace"
          - Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bertrand.RoonController
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_GENERATION_LIBRARY: YES
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "6.0"
        CODE_SIGN_ENTITLEMENTS: RoonController.entitlements
        MACOSX_DEPLOYMENT_TARGET: "12.0"
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: "Roon Controller"

  RoonControllerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    dependencies:
      - target: RoonController
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bertrand.RoonControllerTests
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "12.0"
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Roon Controller.app/Contents/MacOS/Roon Controller"
        BUNDLE_LOADER: "$(TEST_HOST)"
